# Import Libraries

In [62]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Import dataset

In [63]:
dataset=pd.read_csv('train.csv')
dataset2=pd.read_csv('test.csv')
# num_missing=(dataset[[2,4,5,6,7,9,11]]==np.nan).sum()
# print(num_missing)
# print(dataset.head())
# print(dataset['Survived'].value_counts())
y_train=dataset.iloc[:, 1:2].values
#print(y_train)
IDtest=dataset2["PassengerId"]
X_train=dataset.iloc[:, 4:8].values
X_test=dataset2.iloc[:, 3:7].values
# print(dataset['Embarked'].value_counts())
X_train= np.c_[dataset.iloc[:, 2:3].values,X_train]
X_train= np.c_[dataset.iloc[:, 9:10].values,X_train]
##
X_test= np.c_[dataset2.iloc[:, 1:2].values,X_test]
X_test= np.c_[dataset2.iloc[:, 8:9].values,X_test]

# X_train= np.c_[dataset.iloc[:, 11:12].values,X_train]
# print(np.count_nonzero(X_train[:, 0:1]=='S'))
# print(np.count_nonzero(X_train[:, 0:1]=='Q'))
# print(np.count_nonzero(X_train[:, 0:1]=='C'))
# print(np.count_nonzero(X_train[:, 0:1]==np.NAN))
# X_train[:, 0:1].value_counts()
# X_train.insert(0, dataset.iloc[:, 2:3].values)
# X_train.insert(0, dataset.iloc[:, 9:10].values)
# X_train.insert(0, dataset.iloc[:, 11:12].values)
print(X_test[0])
# print(891-168-77-644)
print(X_train[0])
print(IDtest)

[7.8292 3 'male' 34.5 0 0]
[7.25 3 'male' 22.0 1 0]
0       892
1       893
2       894
3       895
4       896
       ... 
413    1305
414    1306
415    1307
416    1308
417    1309
Name: PassengerId, Length: 418, dtype: int64


# Fill missing data

In [64]:
from sklearn.impute import SimpleImputer
imputer =SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X_train[:, 3:4])
X_train[:,3:4]=imputer.transform(X_train[:, 3:4])
# print(len(X_train[0]))
# print(X_train[0])
imputer.fit(X_test[:, 3:4])
X_test[:,3:4]=imputer.transform(X_test[:, 3:4])
imputer.fit(X_test[:, 0:1])
X_test[:,0:1]=imputer.transform(X_test[:, 0:1])
print(X_test[0])
print(X_train[0])

[7.8292 3 'male' 34.5 0 0]
[7.25 3 'male' 22.0 1 0]


 Encoding *Gender*

In [65]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X_train[:, 2] = le.fit_transform(X_train[:, 2])
le1 = LabelEncoder()
X_test[:, 2] = le1.fit_transform(X_test[:, 2])
print(X_test[0])
print(X_train[0])

[7.8292 3 1 34.5 0 0]
[7.25 3 1 22.0 1 0]


In [66]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
print(X_train)
# print(X_test)

[[-0.50244517  0.82737724  0.73769513 -0.5924806   0.43279337 -0.47367361]
 [ 0.78684529 -1.56610693 -1.35557354  0.63878901  0.43279337 -0.47367361]
 [-0.48885426  0.82737724 -1.35557354 -0.2846632  -0.4745452  -0.47367361]
 ...
 [-0.17626324  0.82737724 -1.35557354  0.          0.43279337  2.00893337]
 [-0.04438104 -1.56610693  0.73769513 -0.2846632  -0.4745452  -0.47367361]
 [-0.49237783  0.82737724  0.73769513  0.17706291 -0.4745452  -0.47367361]]


In [67]:
from sklearn.svm import SVC
classifier =SVC(kernel='rbf' ,random_state=0)
classifier.fit(X_train,y_train)

C:\Users\SHAMMI\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVC(random_state=0)

In [68]:
y_pred=classifier.predict(X_train)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_train.reshape(len(y_train),1)),1))

[[0 0]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 1]
 [0 0]]


In [69]:
# test_Survived = pd.Series(votingC.predict(test), name="Survived")

y1=pd.Series(classifier.predict(X_test), name="Survived")
y1=(y1>0.5)
y1=y1*1
print(y1)

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int32


In [70]:
# print(np.shape(y1))
# print(np.all(y1,axis=1))

results = pd.concat([IDtest,y1],axis=1)

results.to_csv("final.csv",index=False)
print(results)

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]


TypeError: sequence item 0: expected str instance, numpy.bool_ found